config/routes.rb
Rails.application.routes.draw do
  post "/graphql", to: "graphql#execute"

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  devise_for :admins
  devise_for :users, skip: [:sessions,:passwords]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
      get 'forgotpassword', to: 'devise/passwords#new', as: :new_user_password
      post 'resetpassword', to: 'devise/passwords#create', as: :user_password
      get 'editpassword', to: 'devise/passwords#edit',  as: :edit_user_password
      get 'resetpassword', to: 'devise/passwords#new'
      patch 'resetpassword', to: 'devise/passwords#update'
      put 'resetpassword', to: 'devise/passwords#update'
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :deals do
    resources :surveys
  end
  root to: 'deals#index'
  get 'searchable' => 'deals#searchable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :deals
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :surveys

  has_attached_file :image, styles: { large: "400x400>",  medium: "300x300>", thumb: "200x200>"},
                            :default_url => "/system/avatars/:style/missing.png",
                            :url  => "/system/:attachment/:id/:style_:filename",
                            :path => ":rails_root/public/system/:attachment/:id/:style_:filename"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def trim
    title.downcase.gsub(" ", "-")  
  end

  def to_param
    "#{id}-#{trim}"
  end

end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :deal
  belongs_to :user

  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :deals
  has_many :surveys
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    root_path
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :find_deal,only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  helper DealsHelper

  def index
    if params[:category].blank?
    @deals = Deal.paginate(:page => params[:page],:per_page => 10).order("created_at desc")
    else 
      @category_id = Category.find_by(name: params[:category]).id
      @deals = Deal.paginate(:page => params[:page],:per_page => 20).where(:category_id => @category_id)
    end
  end

  def new 
    @deal = current_user.deals.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @deal = current_user.deals.build(deal_params)
    @deal.category_id = params[:category_id]
    if @deal.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    if @deal.surveys.blank?
      @average_surveys = 0
    else
      @average_surveys = @deal.surveys.average(:rating)
    end
  end 

  def edit
    @categories = Category.all.map{|c| [c.name,c.id]}
  end

  def update
    if @deal.update(deal_params)
      redirect_to @deal
    else
      render :edit
    end
  end

  def destroy
    if @deal.destroy
      redirect_to root_path
    end
  end
  
  def searchable
    if params[:search].blank?
      redirect_to root_path
    else
      searchword = params[:search]
      @deals = Deal.where("lower(title) LIKE ? or lower(description) LIKE ?", "%#{searchword.downcase}%","%#{searchword.downcase}%")
    end
  end

  private

  def deal_params
    params.require(:deal).permit(:title,:description,:link,:link1,:category_id,:image)
  end

  def find_deal
    @deal = Deal.find(params[:id])
  end

end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # before_action :authenticate_user!
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      current_user: current_user,
    }
    result = Dealcart18Schema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :find_deal
  before_action :find_survey, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  def index

  end
  def new
    @survey = Survey.new
  end
  def create
    @survey = Survey.new(survey_params)
    @survey.deal_id = @deal.id
    @survey.user_id = current_user.id
    @survey.ip_address = request.remote_ip
    if @survey.save
      redirect_to deal_path(@deal)
    else
      render :new
    end
  end
  def show

  end
  def edit

  end
  def update
    @survey.ip_address = request.remote_ip
    if @survey.update(survey_params)
      redirect_to deal_path(@deal)
    else
      render :edit
    end

  end
  def destroy
    @survey.destroy
    redirect_to deal_path(@deal)
  end

  private
    def survey_params
      params.require(:survey).permit(:rating,:comment, :ip_address, :avatar)
    end

    def find_deal
      @deal = Deal.find(params[:deal_id])
    end

    def find_survey
      @survey=Survey.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/deals/_form.html.erb
<%= simple_form_for @deal, html: { multipart: true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories),{ :class => 'btn btn-block btn-default btn-default' }) %>
  <%= f.input :image, as: :file %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :link %>
  <%= f.input :link1 %>
  <%= f.button :submit %> 
<% end %>

app/views/deals/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="signup-form">
    <%= simple_form_for @deal, html: { multipart: true } do |f| %>
      <%= f.input :category_id, collection: @categories, prompt: "Select a catagory" %>
      <%= f.input :image, as: :file %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :link %>
      <%= f.input :link1 %>
      <%= f.button :submit %> 
    <% end %>
  </div>
</div>

app/views/deals/index.html.erb
<%= render 'shared/carousel' %>
<div class="container-fluid">

  <div class = "container-fluid col-md-9 data">

    <h3><%= params[:category] %></h3>
   
      <% if @deals.count == 0 %>
       <h1>no deals avilable</h1>
      <% else %>
        <% @deals.all.each do |deal| %>
          <div class="row deal-panel">
            <h1 class="show"><%= link_to deal.title,deal_path(deal)%></h1>
          <div class="col-md-4 col-sm-12 col-xs-12 deal-img">
            <%= image_tag deal.image.url(:large), class: "img-responsive" %><br />
            <p class="deal-time"><%= time_ago_in_words(deal.created_at) %> ago </p>
          </div>
          <div class="col-md-8 col-sm-12 col-xs-12 deal-info text-justify">
             
            <%= (deal.description).truncate_words(70)%>
            <h4><%= link_to "Read more",deal_path(deal)%>...</h4>
             
            <h4>More Deals:</h4>
            <p><%= link_to deal.link , url_with_protocol(deal.link1), :target => '_blank' %></p>
                
          </div>
        </div>
        <% end %>
      <% end %>
  </div>
  <div class="container col-md-3" style="background-color: red">
    <h1>data</h1>
  </div>
  <%= will_paginate @deals, renderer: BootstrapPagination::Rails %>
</div>

<% @deals.all.each do |deal| %>
  <%= link_to image_tag(deal.image.url(:large)), deal.image.url(:large), {  'data-toggle' => 'lightbox', "data-gallery"=>"example-gallery"} %>
<% end %>

app/views/deals/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="signup-form">
    <%= render "form" %>
  </div>
</div>

app/views/deals/searchable.html.erb
<h1>searching for '<%= params[:search] %>'</h1>

  <% if @deals.size.zero? %>
    <h1>no results found</h1>

  <% else %>
    <p><%= pluralize(@deals.size,'Deal') %> found</p>
    <div class = "container">

    <% @deals.all.each do |deal| %>
      <div class="row deal-panel">
        <h1 class="show"><%= link_to deal.title,deal_path(deal)%></h1>
        <div class="col-md-4 col-sm-12 col-xs-12 deal-img">
          <%= image_tag deal.image.url(:large), class: "img-responsive" %><br />
          <p class="deal-time"><%= time_ago_in_words(deal.created_at) %> ago. </p>
        </div>
        <div class="col-md-8 col-sm-12 col-xs-12 deal-info text-justify">
          <%= (deal.description).truncate_words(70)%>
          <h4><%= link_to "Read more",deal_path(deal)%>...</h4>

          <h4>More Deals:</h4>
          <p><%= link_to deal.link , url_with_protocol(deal.link1), :target => '_blank' %></p>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/deals/show.html.erb
<div class = "container data">        
  <div class="row deal-panel">

    <h1 class="show"><%= link_to @deal.title,deal_path(@deal)%></h1>
    <div class="col-md-4 col-sm-12 col-xs-12 deal-img">
      <%= image_tag @deal.image.url(:large), class: "img-responsive" %><br />
      <p class="deal-time"><%= time_ago_in_words(@deal.created_at) %> ago </p>
      <%= link_to "Back" ,root_path %> <br /> 
      <% if user_signed_in? %>
        <% if @deal.user_id == current_user.id %>
          <%= link_to "Edit" ,edit_deal_path(@deal), class: "btn btn-xs btn-warning glyphicon glyphicon-pencil" %> |
          <%= link_to "Delete", deal_path(@deal),method: :delete,data: {confirm: "Thinks onces again"}, class: "btn btn-xs btn-warning"  %>
        <% end %>
      <% end %>  
    </div>

    <div class="col-md-8 col-sm-12 col-xs-12 deal-info text-justify">
      <p><%= @deal.description%><br /></p>
      <div class="average-survey-rating" data-score=<%=  @average_surveys %>></div> 
        <span>Based on <%= @deal.surveys.count%> survey</span>
        <h3>buy: <a href="<%= @deal.link1 %>" target=_blank><%= @deal.link %></a></h3>

        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Rate this deal
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Your Review</h4>
              </div>
              <% if user_signed_in? %>
              <div class="modal-body">
                <%= simple_form_for([@deal, @deal.surveys.build]) do |f| %>
                  <div id="rating-form">
                    <label>Rating</label>
                  </div>
                  <%= f.input :comment %>
                  <%= f.button :submit, "Rate it!" %>
                <% end %>
              </div>
              <% else %>
              <h5>You must login<%= link_to "Sign In", new_user_session_path %></h5>
              <% end %>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>    
      </div> 
    </div> 
      
</div>
<div class="survey">
  <% if @deal.surveys.count > 0 %>
    <%= render @deal.surveys %><br />
  <% end %>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'survey[rating]'
  });
</script>

<script>
  $('.survey-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-survey-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dealcart18</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/assets/LOGO.png" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %> 
  </body>
</html>

app/views/shared/_carousel.html.erb
<div id="Heroimage" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#Heroimage" data-slide-to="0" class="active"></li>
    <li data-target="#Heroimage" data-slide-to="1"></li>
    <li data-target="#Heroimage" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

    <div class="item active">
      <%= image_tag("image.jpg", :alt => "image") %>
      <div class="carousel-caption">
        first here
      </div>
    </div>

    <div class="item">
      <%= image_tag("image.jpg", :alt => "image") %>
      <div class="carousel-caption">
        second here
      </div>
    </div>

    <div class="item">
      <%= image_tag("image.jpg", :alt => "image") %>
      <div class="carousel-caption">
        <li><%= link_to "Sign In", new_user_session_path %></li>
      </div>
    </div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#Heroimage" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#Heroimage" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_footer.html.erb
    <footer class="footer-panel">

      <div class="footer-right">

        <a href="www.facebook.com"><i class="fa fa-facebook"></i></a>
        <a href="www.twitter.com"><i class="fa fa-twitter"></i></a>
        <a href="www.linkedin.com"><i class="fa fa-linkedin"></i></a>
        <a href="www.github.com"><i class="fa fa-github"></i></a>

      </div>

      <div class="footer-left">
        
        <p>Dealkart &copy; 2016</p>

        <p class="footer-links">

          <a href="#">About</a>

          <a href="#">Faq</a>

          <a href="#">Contact</a>
        </p>


      </div>

    </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default"> 
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home" , root_path%></li>
        <li class="navbar-form navbar-left" role="search">
        <%= form_tag searchable_path, method: 'get' do  %>
          <%= text_field_tag :search, params[:search] ,:class => "form-control", :placeholder => "Search" %>  
          <%= submit_tag "Search", name: nil, :class => "btn btn-default" %>
        <% end %>
        </li>
      </ul> 
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to "Add a big deal", new_deal_path%></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% elsif user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<header><%= image_tag("LOGO.png", height: '100px', width: '100%')  %></header> 

<div  class="cat-nav container-fuild">
  <ul class="cat" style="border:1PX solid grey ">
    <% Category.all.each do |category| %>
      <li class="cat-link">
        <%= link_to category.name, deals_path(category: category.name)%>
      </li>
    <% end %>
  </ul>
</div>

app/views/surveys/_form.html.erb
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for([@deal, @deal.surveys.build]) do |f| %>
          <div id="rating-form">
            <label>Rating</label>
          </div>
          <%= f.input :comment %>
          <%= f.input :avatar, as: :file %>
          <%= f.button :submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'survey[rating]'
  });
</script>

app/views/surveys/_survey.html.erb
<div class="container survey">
<h3 style="color: green">Your rating:  </h3>
<div class = "survey-rating" data-score="<%= survey.rating %>"></div>

<p class="user-comment"><%= survey.comment %></p>

<div>
  <% if survey.avatar.url.present? %>
    <%= image_tag(survey.avatar.thumb.url) %>
  <% end %>
</div>

<% if user_signed_in? %>
  <% if survey.user_id == current_user.id %>
    <%= link_to "edit", edit_deal_survey_path(survey.deal, survey), class: "btn btn-xs btn-info glyphicon glyphicon-pencil" %>
    <%= link_to "delete", deal_survey_path(survey.deal, survey),method: :delete,data: {confirm: "Stay connected"}, class: "btn btn-xs btn-info" %>
  <% end %>
<% end %>
</div>

app/views/surveys/edit.html.erb
<h1>edit</h1>
<%= simple_form_for([@deal, @survey]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.input :avatar, as: :file %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'survey[rating]'
  });
</script>

app/views/surveys/new.html.erb
<%= render "form" %>